apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "tom-redis.fullname" . }}
  labels: {{- include "tom-redis.labels" . | nindent 4 }}
data:
  redis.conf: |-
{{- if .Values.enableAof }}
    appendonly yes
{{- end }}

{{- if .Values.disableRdb }}
    save ""
{{- end }}

    dir {{ .Values.main.persistence.path }}

{{- if .Values.main.disableCommands }}
{{- range .Values.main.disableCommands }}
    rename-command {{ . }} ""
{{- end }}
{{- end }}

{{/*{{- if .Values.commonConfigMap }}*/}}
{{/*    # User-supplied configuration:*/}}
{{/*{{- tpl .Values.commonConfigMap . | nindent 4 }}*/}}
{{/*{{- end }}*/}}

  master.conf: |-
{{/*{{- if .Values.master.configmap }}*/}}
{{/*    # User-supplied master configuration:*/}}
{{/*{{- tpl .Values.master.configmap . | nindent 4 }}*/}}
{{/*{{- end }}*/}}

  replica.conf: |-
{{- if .Values.slaveReadOnly }}
    slave-read-only yes
{{- end }}

{{/*    dir {{ .Values.slave.persistence.path }}*/}}
{{/*{{- if .Values.slave.configmap }}*/}}
{{/*    # User-supplied slave configuration:*/}}
{{/*{{- tpl .Values.slave.configmap . | nindent 4 }}*/}}
{{/*{{- end }}*/}}
{{/*{{- if .Values.slave.disableCommands }}*/}}
{{/*{{- range .Values.slave.disableCommands }}*/}}
{{/*    rename-command {{ . }} ""*/}}
{{/*{{- end }}*/}}
{{/*{{- end }}*/}}

  sentinel.conf: |-
    dir "/tmp"
    bind 0.0.0.0
    port {{ .Values.sentinel.port }}
    sentinel monitor {{ .Values.sentinel.masterSet }} {{ include "tom-redis.masterHost" .}} {{ .Values.redisPort }} {{ .Values.sentinel.quorum }}
    sentinel down-after-milliseconds {{ .Values.sentinel.masterSet }} {{ .Values.sentinel.downAfterMilliseconds }}
    sentinel failover-timeout {{ .Values.sentinel.masterSet }} {{ .Values.sentinel.failoverTimeout }}
    sentinel parallel-syncs {{ .Values.sentinel.masterSet }} {{ .Values.sentinel.parallelSyncs }}
