apiVersion: v1
kind: Secret
metadata:
  name: {{ template "tom-redis.secretName" . }}
  labels: {{- include "tom-redis.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.secretPasswordKey }}: {{ .Values.password | b64enc | quote }}
